/**
 * Supported currencies of OFX obtained from here:
 * https://www.ofx.com/en-au/faqs/what-currencies-can-i-transfer-with-ofx/
 *
 * This file contains a map of currency codes to their respective currency names.
 * Usage: validate supported currencies from user input.
 */
export const currencies = new Map([
    ['AED', 'United Arab Emirates Dirham'],
    ['AUD', 'Australian Dollar'],
    ['CAD', 'Canadian Dollar'],
    ['CHF', 'Swiss Franc'],
    ['CNH', 'Offshore Chinese Renminbi'],
    ['CZK', 'Czech Krouna'],
    ['DKK', 'Danish Kroner'],
    ['EUR', 'Euro'],
    ['FJD', 'Fijian Dollar'],
    ['GBP', 'Pound Sterling'],
    ['HKD', 'Hong Kong Dollar'],
    ['HUF', 'Hungarian Forint'],
    ['IDR', 'Indonesian Rupiah'],
    ['ILS', 'Israeli Shekel'],
    ['INR', 'Indian Rupee'],
    ['JPY', 'Japanese Yen'],
    ['MXN', 'Mexican Peso'],
    ['MYR', 'Malaysian Ringgit'],
    ['NOK', 'Norwegian Kroner'],
    ['NZD', 'New Zealand Dollar'],
    ['PHP', 'Philippine Peso'],
    ['PLN', 'Polish Zloty'],
    ['SBD', 'Solomon Island Dollar'],
    ['SEK', 'Swedish Kroner'],
    ['SGD', 'Singapore Dollar'],
    ['THB', 'Thailand Baht'],
    ['TOP', 'Tongan Pa’anga'],
    ['TRY', 'Turkish Lira'],
    ['USD', 'US Dollar'],
    ['VUV', 'Vanuatu Vatu'],
    ['WST', 'Samoan Tala'],
    ['XPF', 'CFP Franc'],
    ['ZAR', 'South African Rand'],
    ['AZN', 'Azerbaijani Manat'],
    ['BGN', 'Bulgarian Lev'],
    ['BHD', 'Bahraini Dinar'],
    ['BND', 'Brunei Dollar'],
    ['CNY', 'Chinese Yuan Renminbi'],
    ['EGP', 'Egyptian Pound'],
    ['KRW', 'South Korean Won'],
    ['KWD', 'Kuwaiti Dinar'],
    ['LKR', 'Sri Lankan Rupee'],
    ['MAD', 'Moroccan Dirham'],
    ['MGA', 'Malagasy Ariary'],
    ['OMR', 'Omani Rial'],
    ['PEN', 'Peruvian Nuevo Sol'],
    ['PGK', 'Papua New Guinea Kina'],
    ['PKR', 'Pakistan Rupee'],
    ['SAR', 'Saudi Riyal'],
    ['SCR', 'Seychellois Rupee'],
    ['TWD', 'Taiwanese Dollar'],
    ['TZS', 'Tanzanian Shilling'],
    ['VND', 'Vietnamese Dong'],
    ['XOF', 'West African CFA Franc'],
]);
